# Usa imagem oficial do Node 22
FROM node:22

# Entra de trabalho
WORKDIR /app

# Copia arquivos necessários para instalar as dependencia node_modules EM TEMPO DE BUILD
COPY package*.json ./
COPY App/server.js ./App/server.js

# Instala dependências + nodemon para "ouvir" as mudanças
RUN npm install -g nodemon && npm install

# EXPOSE 3000

# Comando padrão ao iniciar o container
ENTRYPOINT ["npm", "run", "dev"]
